services:
  nest1_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: nest1_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5102:5432'

  nest1_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest1_app
    environment:
      - PORT=${PORT}
    ports:
      - '5100:3010'
    depends_on:
      - nest1_db
    volumes:
      - ./src:/app/src

  nest1_pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest1_pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5101:80'
    depends_on:
      - nest1_db